apiVersion: v1
kind: Service
metadata:
  name: hack-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: app
  - port: 443
    targetPort: 443
    name: app-ssl
  selector:
    app: hack-app